# Importing Kaggle dataset

In [ ]:
import kagglehub
path = kagglehub.dataset_download("jakewright/house-price-data")

Downloading to /root/.cache/kagglehub/datasets/jakewright/house-price-data/5.archive...

100%|██████████| 48.5M/48.5M [00:00<00:00, 102MB/s]

Extracting files...

# Importing dependencies and library

In [ ]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Loading dataset

In [ ]:
os.listdir(path)

['kaggle_london_house_price_data.csv',
 'kaggle_london_house_price_data.parquet']

On this dataset we get Kaggle dataset link we have two file one is csv and parquet 'kaggle_london_house_price_data.csv' and 'kaggle_london_house_price_data.parquet' both dataset have the same number of columns and features all the value are same but size is different so On this project i used the parquet dataset because lingt weight and suitable for large dataset.

In [ ]:
data_csv = os.path.join(path, 'kaggle_london_house_price_data.csv')

In [ ]:
data_parquet = os.path.join(path, 'kaggle_london_house_price_data.parquet')

In [ ]:
df_csv = pd.read_csv(data_csv)

In [ ]:
df_parquet = pd.read_parquet(data_parquet)

# Exploratory Data Analysis

## Understading of dataset

In [ ]:
df_csv.shape

(418201, 28)

In [ ]:
df_parquet.shape

(418201, 28)

In [ ]:
df_csv.head()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN

In [ ]:
df_parquet.head()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN

In [ ]:
df_parquet.tail()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
418196,"9 Harvard Road, London, SE13 6SE",SE13 6SE,England,SE13,51.452919,-0.010221,2.0,3.0,123.0,2.0,...,711000.0,HIGH,2025-01-10T11:04:57.114Z,27000.0,4.153846,2024-09-27,2024-09-27,650000,17.117117,95000.0
418197,"Lower Ground Floor Flat 5, Northwood Hall, Hor...",N6 5PE,England,N6,51.571692,-0.137007,1.0,2.0,60.0,1.0,...,473000.0,HIGH,2025-01-10T11:04:57.114Z,10000.0,2.272727,2024-09-27,2024-09-27,440000,2.325581,10000.0
418198,"17 Merritt Road, London, SE4 1DU",SE4 1DU,England,SE4,51.456054,-0.035073,2.0,3.0,100.0,1.0,...,853000.0,HIGH,2025-01-10T11:04:57.114Z,38000.0,4.909561,2024-09-27,2024-09-27,774000,128.655835,435500.0
418199,"15 Chester Row, London, SW1W 9JF",SW1W 9JF,England,SW1W,51.493587,-0.152122,3.0,4.0,218.0,2.0,...,5975000.0,MEDIUM,2025-01-10T11:04:57.114Z,-818000.0,-13.088000,2024-09-27,2024-09-27,6250000,73.611111,2650000.0
418200,"56 Whiteley Road, London, SE19 1JT",SE19 1JT,England,SE19,51.424412,-0.090256,1.0,5.0,154.0,2.0,...,1031000.0,HIGH,2025-01-10T11:04:57.114Z,55000.0,5.876011,2024-09-27,2024-09-27,927500,692.735043,810500.0

In [ ]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418201 entries, 0 to 418200
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                418201 non-null  object
 1   postcode                                   418201 non-null  object
 2   country                                    418201 non-null  object
 3   outcode                                    418201 non-null  object
 4   latitude                                   418201 non-null  float64
 5   longitude                                  418201 non-null  float64
 6   bathrooms                                  340270 non-null  float64
 7   bedrooms                                   377665 non-null  float64
 8   floorAreaSqM                               392991 non-null  float64
 9   livingRooms                                357701 non-null  float64
 10  tenure                                     406689 non-null  object
 11  propertyType                               417065 non-null  object
 12  currentEnergyRating                        333675 non-null  object
 13  rentEstimate_lowerPrice                    416460 non-null  float64
 14  rentEstimate_currentPrice                  416460 non-null  float64
 15  rentEstimate_upperPrice                    416460 non-null  float64
 16  saleEstimate_lowerPrice                    417561 non-null  float64
 17  saleEstimate_currentPrice                  417561 non-null  float64
 18  saleEstimate_upperPrice                    417561 non-null  float64
 19  saleEstimate_confidenceLevel               417561 non-null  object
 20  saleEstimate_ingestedAt                    417561 non-null  object
 21  saleEstimate_valueChange.numericChange     417561 non-null  float64
 22  saleEstimate_valueChange.percentageChange  417561 non-null  float64
 23  saleEstimate_valueChange.saleDate          417561 non-null  object
 24  history_date                               418201 non-null  object
 25  history_price                              418201 non-null  int64
 26  history_percentageChange                   237982 non-null  float64
 27  history_numericChange                      237982 non-null  float64
dtypes: float64(16), int64(1), object(11)
memory usage: 89.3+ MB

In [ ]:
df_parquet.info()

### Converting date time

In [ ]:
cols = [
    'saleEstimate_ingestedAt',
    'saleEstimate_valueChange.saleDate',
    'history_date'
]

for col in cols:
    print(f"{col}: ")
    print("Sample values:")
    print(df_parquet[col].head(10))
    print("\nUnique sample values:")
    print(df_parquet[col].dropna().unique()[:10])

saleEstimate_ingestedAt:
Sample values:
0    2024-10-07T13:26:59.894Z
1    2024-10-07T13:26:59.894Z
2    2025-01-10T11:04:57.114Z
3    2024-10-07T13:26:59.894Z
4    2024-10-07T13:26:59.894Z
5    2024-10-07T13:26:59.894Z
6    2024-10-07T13:26:59.894Z
7    2025-01-10T11:04:57.114Z
8    2024-10-07T13:26:59.894Z
9    2025-01-10T11:04:57.114Z
Name: saleEstimate_ingestedAt, dtype: object

Unique sample values:
['2024-10-07T13:26:59.894Z' '2025-01-10T11:04:57.114Z'
 '2025-02-06T14:05:28.374Z' '2024-11-05T11:25:48.799Z']
saleEstimate_valueChange.saleDate:
Sample values:
0    2010-03-30
1    2000-05-26
2    2019-09-04
3    2024-01-25
4    2022-12-14
5    2021-09-30
6    2021-12-06
7    2016-09-27
8    2022-02-10
9    2022-12-14
Name: saleEstimate_valueChange.saleDate, dtype: object

Unique sample values:
['2010-03-30' '2000-05-26' '2019-09-04' '2024-01-25' '2022-12-14'
 '2021-09-30' '2021-12-06' '2016-09-27' '2022-02-10' '2024-04-19']
history_date:
Sample values:
0    1995-01-02
1    1995-01-02
2    1995-01-03
3    1995-01-03
4    1995-01-03
5    1995-01-03
6    1995-01-03
7    1995-01-03
8    1995-01-03
9    1995-01-03
Name: history_date, dtype: object

Unique sample values:
['1995-01-02' '1995-01-03' '1995-01-04' '1995-01-05' '1995-01-06'
 '1995-01-09' '1995-01-10' '1995-01-11' '1995-01-12' '1995-01-13']

In [ ]:
df_parquet['saleEstimate_ingestedAt'] = pd.to_datetime(df_parquet['saleEstimate_ingestedAt'], errors='coerce')
df_parquet['saleEstimate_valueChange.saleDate'] = pd.to_datetime(df_parquet['saleEstimate_valueChange.saleDate'], errors='coerce')
df_parquet['history_date'] = pd.to_datetime(df_parquet['history_date'], errors='coerce')

In [ ]:
df_parquet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418201 entries, 0 to 418200
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                418201 non-null  object
 1   postcode                                   418201 non-null  object
 2   country                                    418201 non-null  object
 3   outcode                                    418201 non-null  object
 4   latitude                                   418201 non-null  float64
 5   longitude                                  418201 non-null  float64
 6   bathrooms                                  340270 non-null  float64
 7   bedrooms                                   377665 non-null  float64
 8   floorAreaSqM                               392991 non-null  float64
 9   livingRooms                                357701 non-null  float64
 10  tenure                                     406689 non-null  object
 11  propertyType                               417065 non-null  object
 12  currentEnergyRating                        333675 non-null  object
 13  rentEstimate_lowerPrice                    416460 non-null  float64
 14  rentEstimate_currentPrice                  416460 non-null  float64
 15  rentEstimate_upperPrice                    416460 non-null  float64
 16  saleEstimate_lowerPrice                    417561 non-null  float64
 17  saleEstimate_currentPrice                  417561 non-null  float64
 18  saleEstimate_upperPrice                    417561 non-null  float64
 19  saleEstimate_confidenceLevel               417561 non-null  object
 20  saleEstimate_ingestedAt                    417561 non-null  datetime64[ns, UTC]
 21  saleEstimate_valueChange.numericChange     417561 non-null  float64
 22  saleEstimate_valueChange.percentageChange  417561 non-null  float64
 23  saleEstimate_valueChange.saleDate          417561 non-null  datetime64[ns]
 24  history_date                               418201 non-null  datetime64[ns]
 25  history_price                              418201 non-null  int64
 26  history_percentageChange                   237982 non-null  float64
 27  history_numericChange                      237982 non-null  float64
dtypes: datetime64[ns, UTC](1), datetime64[ns](2), float64(16), int64(1), object(8)
memory usage: 89.3+ MB

### Missing values analysis

In [ ]:
df_parquet.isnull().sum()

fullAddress                                       0
postcode                                          0
country                                           0
outcode                                           0
latitude                                          0
longitude                                         0
bathrooms                                     77931
bedrooms                                      40536
floorAreaSqM                                  25210
livingRooms                                   60500
tenure                                        11512
propertyType                                   1136
currentEnergyRating                           84526
rentEstimate_lowerPrice                        1741
rentEstimate_currentPrice                      1741
rentEstimate_upperPrice                        1741
saleEstimate_lowerPrice                         640
saleEstimate_currentPrice                       640
saleEstimate_upperPrice                         640
saleEstimate_confidenceLevel                    640
saleEstimate_ingestedAt                         640
saleEstimate_valueChange.numericChange          640
saleEstimate_valueChange.percentageChange       640
saleEstimate_valueChange.saleDate               640
history_date                                      0
history_price                                     0
history_percentageChange                     180219
history_numericChange                        180219
dtype: int64

'fullAddress' is droped because it does not need us.

In [ ]:
df_parquet.drop(columns=['fullAddress'], inplace=True)

In [ ]:
missing = df_parquet.isnull().sum().sort_values(ascending=False)
missing_percent = (df_parquet.isnull().mean() * 100).sort_values(ascending=False)

missing_df = pd.DataFrame({
    'Missing Count': missing,
    'Missing %': missing_percent
})

print(missing_df)

                                           Missing Count  Missing %
history_numericChange                             180219  43.093871
history_percentageChange                          180219  43.093871
currentEnergyRating                                84526  20.211812
bathrooms                                          77931  18.634819
livingRooms                                        60500  14.466728
bedrooms                                           40536   9.692947
floorAreaSqM                                       25210   6.028202
tenure                                             11512   2.752743
rentEstimate_lowerPrice                             1741   0.416307
rentEstimate_upperPrice                             1741   0.416307
rentEstimate_currentPrice                           1741   0.416307
propertyType                                        1136   0.271640
saleEstimate_confidenceLevel                         640   0.153036
saleEstimate_ingestedAt                              640   0.153036
saleEstimate_valueChange.numericChange               640   0.153036
saleEstimate_valueChange.saleDate                    640   0.153036
saleEstimate_upperPrice                              640   0.153036
saleEstimate_lowerPrice                              640   0.153036
saleEstimate_currentPrice                            640   0.153036
saleEstimate_valueChange.percentageChange            640   0.153036
longitude                                              0   0.000000
country                                                0   0.000000
outcode                                                0   0.000000
postcode                                               0   0.000000
latitude                                               0   0.000000
history_price                                          0   0.000000
history_date                                           0   0.000000

## Descriptive Analysis

In [ ]:
df_parquet.describe()

,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,rentEstimate_lowerPrice,rentEstimate_currentPrice,rentEstimate_upperPrice,saleEstimate_lowerPrice,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,history_price,history_percentageChange,history_numericChange
count,418201.000000,418201.000000,340270.000000,377665.000000,392991.000000,357701.000000,416460.000000,416460.000000,416460.000000,4.175610e+05,4.175610e+05,4.175610e+05,4.175610e+05,417561.000000,4.182010e+05,237982.000000,2.379820e+05
mean,51.507522,-0.101426,1.444265,2.474884,98.926543,1.282275,3299.054171,3639.487466,3980.117298,8.312692e+05,9.045188e+05,9.777633e+05,2.886077e+04,29.278605,6.395840e+05,105.877778,2.528741e+05
std,0.056171,0.086930,0.724478,1.160506,55.938911,0.574412,3168.625404,3487.801945,3808.508868,8.088434e+05,9.202917e+05,1.037913e+06,1.080893e+06,362.350731,1.327933e+06,338.849944,8.024032e+05
min,51.385708,-0.347055,1.000000,1.000000,10.000000,1.000000,300.000000,350.000000,400.000000,8.100000e+04,8.900000e+04,9.300000e+04,-1.053770e+08,-99.763196,1.000000e+04,-99.890110,-7.390000e+07
25%,51.464315,-0.155996,1.000000,2.000000,63.000000,1.000000,1800.000000,1950.000000,2100.000000,4.160000e+05,4.460000e+05,4.750000e+05,1.100000e+04,2.105263,2.280000e+05,17.833333,4.849500e+04
50%,51.501581,-0.108482,1.000000,2.000000,84.000000,1.000000,2350.000000,2600.000000,2850.000000,5.810000e+05,6.220000e+05,6.630000e+05,3.500000e+04,6.260870,4.000000e+05,52.857143,1.300000e+05
75%,51.548515,-0.043582,2.000000,3.000000,116.000000,1.000000,3550.000000,3950.000000,4300.000000,9.130000e+05,9.840000e+05,1.054000e+06,8.600000e+04,13.554987,6.650000e+05,114.285714,2.870000e+05
max,51.665823,0.139249,9.000000,9.000000,500.000000,9.000000,111500.000000,121200.000000,130900.000000,2.337600e+07,2.922000e+07,3.506400e+07,2.268100e+07,48860.000000,1.058000e+08,48800.770000,6.382000e+07

In [ ]:
df_parquet.describe().T

,count,mean,min,25%,50%,75%,max,std
latitude,418201.0,51.507522,51.385708,51.464315,51.501581,51.548515,51.665823,0.056171
longitude,418201.0,-0.101426,-0.347055,-0.155996,-0.108482,-0.043582,0.139249,0.08693
bathrooms,340270.0,1.444265,1.0,1.0,1.0,2.0,9.0,0.724478
bedrooms,377665.0,2.474884,1.0,2.0,2.0,3.0,9.0,1.160506
floorAreaSqM,392991.0,98.926543,10.0,63.0,84.0,116.0,500.0,55.938911
livingRooms,357701.0,1.282275,1.0,1.0,1.0,1.0,9.0,0.574412
rentEstimate_lowerPrice,416460.0,3299.054171,300.0,1800.0,2350.0,3550.0,111500.0,3168.625404
rentEstimate_currentPrice,416460.0,3639.487466,350.0,1950.0,2600.0,3950.0,121200.0,3487.801945
rentEstimate_upperPrice,416460.0,3980.117298,400.0,2100.0,2850.0,4300.0,130900.0,3808.508868
saleEstimate_lowerPrice,417561.0,831269.215755,81000.0,416000.0,581000.0,913000.0,23376000.0,808843.379724
saleEstimate_currentPrice,417561.0,904518.762528,89000.0,446000.0,622000.0,984000.0,29220000.0,920291.664239
saleEstimate_upperPrice,417561.0,977763.270516,93000.0,475000.0,663000.0,1054000.0,35064000.0,1037913.051264
saleEstimate_valueChange.numericChange,417561.0,28860.767648,-105377000.0,11000.0,35000.0,86000.0,22681000.0,1080893.492314
saleEstimate_valueChange.percentageChange,417561.0,29.278605,-99.763196,2.105263,6.26087,13.554987,48860.0,362.350731
saleEstimate_valueChange.saleDate,417561,2021-11-27 12:28:40.195132928,1995-01-06 00:00:00,2021-07-08 00:00:00,2022-11-30 00:00:00,2023-10-04 00:00:00,2024-09-27 00:00:00,NaN
history_date,418201,2013-08-27 20:59:16.846587904,1995-01-02 00:00:00,2005-03-17 00:00:00,2016-01-21 00:00:00,2022-07-29 00:00:00,2024-09-27 00:00:00,NaN
history_price,418201.0,639584.00439,10000.0,228000.0,400000.0,665000.0,105800000.0,1327933.407839
history_percentageChange,237982.0,105.877778,-99.89011,17.833333,52.857143,114.285714,48800.77,338.849944
history_numericChange,237982.0,252874.079405,-73900000.0,48495.0,130000.0,287000.0,63820000.0,802403.242233

# Save file for visualization.

In [ ]:
save_dir = Path("../data")
save_dir.mkdir(parents=True, exist_ok=True)

save_path = save_dir / "house_price_data.csv"

df_parquet.to_csv(save_path, index=False)

print("Saved to:", save_path.resolve())

Saved to: /data/house_price_data.csv

In [1]:
%run eda.ipynb

Exception: File `'eda.ipynb.py'` not found.

In [2]:
import pandas as pd
df = pd.read_csv("data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'