# Importing Kaggle dataset

In [1]:
import kagglehub
path = kagglehub.dataset_download("jakewright/house-price-data")

Downloading to /root/.cache/kagglehub/datasets/jakewright/house-price-data/5.archive...

100%|██████████| 48.5M/48.5M [00:00<00:00, 99.6MB/s]

Extracting files...

# Importing dependencies and library

In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Loading dataset

In [3]:
os.listdir(path)

['kaggle_london_house_price_data.csv',
 'kaggle_london_house_price_data.parquet']

On this dataset we get Kaggle dataset link we have two file one is csv and parquet 'kaggle_london_house_price_data.csv' and 'kaggle_london_house_price_data.parquet' both dataset have the same number of columns and features all the value are same but size is different so On this project i used the parquet dataset because lingt weight and suitable for large dataset.

In [16]:
data_csv = os.path.join(path, 'kaggle_london_house_price_data.csv')

In [17]:
data_parquet = os.path.join(path, 'kaggle_london_house_price_data.parquet')

In [20]:
df_csv = pd.read_csv(data_csv)

In [21]:
df_parquet = pd.read_parquet(data_parquet)

# Exploratory Data Analysis

## Understading of dataset

In [22]:
df_csv.shape

(418201, 28)

In [23]:
df_parquet.shape

(418201, 28)

In [24]:
df_csv.head()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN

In [25]:
df_parquet.head()

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
0,"Flat 9, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,1.0,1.0,45.0,1.0,...,630000.0,HIGH,2024-10-07T13:26:59.894Z,244000.0,68.539326,2010-03-30,1995-01-02,830000,NaN,NaN
1,"Flat 6, 35 Furnival Street, London, EC4A 1JQ",EC4A 1JQ,England,EC4A,51.517282,-0.110314,NaN,NaN,NaN,NaN,...,660000.0,MEDIUM,2024-10-07T13:26:59.894Z,425000.0,242.857143,2000-05-26,1995-01-02,830000,NaN,NaN
2,"Flat 35, Octavia House, Medway Street, London,...",SW1P 2TA,England,SW1P,51.495505,-0.132379,2.0,2.0,71.0,1.0,...,834000.0,MEDIUM,2025-01-10T11:04:57.114Z,49000.0,6.901408,2019-09-04,1995-01-03,249950,NaN,NaN
3,"24 Chester Court, Lomond Grove, London, SE5 7HS",SE5 7HS,England,SE5,51.478185,-0.092201,1.0,1.0,64.0,1.0,...,407000.0,HIGH,2024-10-07T13:26:59.894Z,28000.0,7.777778,2024-01-25,1995-01-03,32000,NaN,NaN
4,"18 Alexandra Gardens, London, N10 3RL",N10 3RL,England,N10,51.588774,-0.139599,1.0,4.0,137.0,2.0,...,1324000.0,HIGH,2024-10-07T13:26:59.894Z,81000.0,6.864407,2022-12-14,1995-01-03,133000,NaN,NaN

In [26]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418201 entries, 0 to 418200
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                418201 non-null  object
 1   postcode                                   418201 non-null  object
 2   country                                    418201 non-null  object
 3   outcode                                    418201 non-null  object
 4   latitude                                   418201 non-null  float64
 5   longitude                                  418201 non-null  float64
 6   bathrooms                                  340270 non-null  float64
 7   bedrooms                                   377665 non-null  float64
 8   floorAreaSqM                               392991 non-null  float64
 9   livingRooms                                357701 non-null  float64
 10  tenure                                     406689 non-null  object
 11  propertyType                               417065 non-null  object
 12  currentEnergyRating                        333675 non-null  object
 13  rentEstimate_lowerPrice                    416460 non-null  float64
 14  rentEstimate_currentPrice                  416460 non-null  float64
 15  rentEstimate_upperPrice                    416460 non-null  float64
 16  saleEstimate_lowerPrice                    417561 non-null  float64
 17  saleEstimate_currentPrice                  417561 non-null  float64
 18  saleEstimate_upperPrice                    417561 non-null  float64
 19  saleEstimate_confidenceLevel               417561 non-null  object
 20  saleEstimate_ingestedAt                    417561 non-null  object
 21  saleEstimate_valueChange.numericChange     417561 non-null  float64
 22  saleEstimate_valueChange.percentageChange  417561 non-null  float64
 23  saleEstimate_valueChange.saleDate          417561 non-null  object
 24  history_date                               418201 non-null  object
 25  history_price                              418201 non-null  int64
 26  history_percentageChange                   237982 non-null  float64
 27  history_numericChange                      237982 non-null  float64
dtypes: float64(16), int64(1), object(11)
memory usage: 89.3+ MB

In [27]:
df_parquet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418201 entries, 0 to 418200
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                418201 non-null  object
 1   postcode                                   418201 non-null  object
 2   country                                    418201 non-null  object
 3   outcode                                    418201 non-null  object
 4   latitude                                   418201 non-null  float64
 5   longitude                                  418201 non-null  float64
 6   bathrooms                                  340270 non-null  float64
 7   bedrooms                                   377665 non-null  float64
 8   floorAreaSqM                               392991 non-null  float64
 9   livingRooms                                357701 non-null  float64
 10  tenure                                     406689 non-null  object
 11  propertyType                               417065 non-null  object
 12  currentEnergyRating                        333675 non-null  object
 13  rentEstimate_lowerPrice                    416460 non-null  float64
 14  rentEstimate_currentPrice                  416460 non-null  float64
 15  rentEstimate_upperPrice                    416460 non-null  float64
 16  saleEstimate_lowerPrice                    417561 non-null  float64
 17  saleEstimate_currentPrice                  417561 non-null  float64
 18  saleEstimate_upperPrice                    417561 non-null  float64
 19  saleEstimate_confidenceLevel               417561 non-null  object
 20  saleEstimate_ingestedAt                    417561 non-null  object
 21  saleEstimate_valueChange.numericChange     417561 non-null  float64
 22  saleEstimate_valueChange.percentageChange  417561 non-null  float64
 23  saleEstimate_valueChange.saleDate          417561 non-null  object
 24  history_date                               418201 non-null  object
 25  history_price                              418201 non-null  int64
 26  history_percentageChange                   237982 non-null  float64
 27  history_numericChange                      237982 non-null  float64
dtypes: float64(16), int64(1), object(11)
memory usage: 89.3+ MB

In [32]:
df.isnull().sum()

fullAddress                                       0
postcode                                          0
country                                           0
outcode                                           0
latitude                                          0
longitude                                         0
bathrooms                                     77931
bedrooms                                      40536
floorAreaSqM                                  25210
livingRooms                                   60500
tenure                                        11512
propertyType                                   1136
currentEnergyRating                           84526
rentEstimate_lowerPrice                        1741
rentEstimate_currentPrice                      1741
rentEstimate_upperPrice                        1741
saleEstimate_lowerPrice                         640
saleEstimate_currentPrice                       640
saleEstimate_upperPrice                         640
saleEstimate_confidenceLevel                    640
saleEstimate_ingestedAt                         640
saleEstimate_valueChange.numericChange          640
saleEstimate_valueChange.percentageChange       640
saleEstimate_valueChange.saleDate               640
history_date                                      0
history_price                                     0
history_percentageChange                     180219
history_numericChange                        180219
dtype: int64

## Descriptive Analysis

In [28]:
df_parquet.describe()

,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,rentEstimate_lowerPrice,rentEstimate_currentPrice,rentEstimate_upperPrice,saleEstimate_lowerPrice,saleEstimate_currentPrice,saleEstimate_upperPrice,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,history_price,history_percentageChange,history_numericChange
count,418201.000000,418201.000000,340270.000000,377665.000000,392991.000000,357701.000000,416460.000000,416460.000000,416460.000000,4.175610e+05,4.175610e+05,4.175610e+05,4.175610e+05,417561.000000,4.182010e+05,237982.000000,2.379820e+05
mean,51.507522,-0.101426,1.444265,2.474884,98.926543,1.282275,3299.054171,3639.487466,3980.117298,8.312692e+05,9.045188e+05,9.777633e+05,2.886077e+04,29.278605,6.395840e+05,105.877778,2.528741e+05
std,0.056171,0.086930,0.724478,1.160506,55.938911,0.574412,3168.625404,3487.801945,3808.508868,8.088434e+05,9.202917e+05,1.037913e+06,1.080893e+06,362.350731,1.327933e+06,338.849944,8.024032e+05
min,51.385708,-0.347055,1.000000,1.000000,10.000000,1.000000,300.000000,350.000000,400.000000,8.100000e+04,8.900000e+04,9.300000e+04,-1.053770e+08,-99.763196,1.000000e+04,-99.890110,-7.390000e+07
25%,51.464315,-0.155996,1.000000,2.000000,63.000000,1.000000,1800.000000,1950.000000,2100.000000,4.160000e+05,4.460000e+05,4.750000e+05,1.100000e+04,2.105263,2.280000e+05,17.833333,4.849500e+04
50%,51.501581,-0.108482,1.000000,2.000000,84.000000,1.000000,2350.000000,2600.000000,2850.000000,5.810000e+05,6.220000e+05,6.630000e+05,3.500000e+04,6.260870,4.000000e+05,52.857143,1.300000e+05
75%,51.548515,-0.043582,2.000000,3.000000,116.000000,1.000000,3550.000000,3950.000000,4300.000000,9.130000e+05,9.840000e+05,1.054000e+06,8.600000e+04,13.554987,6.650000e+05,114.285714,2.870000e+05
max,51.665823,0.139249,9.000000,9.000000,500.000000,9.000000,111500.000000,121200.000000,130900.000000,2.337600e+07,2.922000e+07,3.506400e+07,2.268100e+07,48860.000000,1.058000e+08,48800.770000,6.382000e+07

In [29]:
df_parquet.describe(include='object')

,fullAddress,postcode,country,outcode,tenure,propertyType,currentEnergyRating,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.saleDate,history_date
count,418201,418201,418201,418201,406689,417065,333675,417561,417561,417561,418201
unique,137760,48392,1,168,4,19,7,3,4,6241,8325
top,"74 Western Beach Apartments, 36 Hanover Avenue...",SW1P 3AN,England,SE18,Leasehold,Purpose Built Flat,D,HIGH,2024-10-07T13:26:59.894Z,2021-06-30,2021-06-30
freq,224,366,418201,8307,247137,110096,135656,300772,282304,2170,1071

In [38]:
df_parquet['saleEstimate_currentPrice'].unique()

array([ 600000.,  759000.,  388000., ..., 7528000., 6493000., 6460000.])